set nocompatible              " be iMproved, required

" vim-plug
call plug#begin('~/.vim/plugged')

" Plug 'Valloric/YouCompleteMe'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'itchyny/lightline.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'preservim/nerdtree'
Plug 'will133/vim-dirdiff'

call plug#end()

" Enable 256-color mode
function! Setup256ColorDiff()
    set t_Co=256
    hi DiffAdd    ctermfg=NONE ctermbg=194
    hi DiffDelete ctermfg=224  ctermbg=224
    hi DiffChange ctermfg=NONE ctermbg=189
    hi DiffText   ctermfg=NONE ctermbg=153 cterm=bold
endfunction

call Setup256ColorDiff()

" remember last position
augroup RestoreCursor
    autocmd!
    autocmd BufReadPost *
        \ if line("'\"") >= 1 && line("'\"") <= line("$") && &filetype !~# 'commit' |
        \   exe "normal! g`\"" |
        \ endif
augroup END

" persistent undo
set undodir=~/.vim/undodir
set undofile

" search settings
set ignorecase
set hlsearch
hi Search ctermbg=44
map <Space> :noh<cr>

syntax on
set nu
set backspace=2

" Normal settings
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" c.vim
let g:c_repo_whitelist = ['workplace/percpu', 'workplace/drgn']

set showtabline=2

" pane management
set splitbelow
set splitright

noremap <C-w>-  :sp<CR>
noremap <C-w><bar>  :vsp<CR>

" go to tab by number
nnoremap <C-t>    :tabnew<CR>
noremap g1 1gt
noremap g2 2gt
noremap g3 3gt
noremap g4 4gt
noremap g5 5gt
noremap g6 6gt
noremap g7 7gt
noremap g8 8gt
noremap g9 9gt
noremap g0 :tablast<cr>

" terminal
nnoremap <C-w>t :terminal<CR>

" ycm
let g:ycm_add_preview_to_completeopt = 1
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_key_list_stop_completion = ['<C-y>', '<Enter>']

nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>
nnoremap <F6> :YcmRestartServer<CR>
nnoremap <leader>h :YcmShowDetailedDiagnostic<CR>
nnoremap <leader>gt :YcmCompleter GoTo<CR>
nnoremap <leader>fi :YcmCompleter FixIt<CR>
nnoremap <leader>gd :YcmCompleter GetDoc<CR>
nnoremap <leader>gtp :YcmCompleter GetType<CR>
nnoremap <leader>gp :YcmCompleter GetParent<CR>
nnoremap <leader>gti :YcmCompleter GoToInclude<CR>
nnoremap <leader>gdf :YcmCompleter GoToDefinition<CR>
nnoremap <leader>gdc :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>yd :YcmDiags<CR>
nmap <leader>c <plug>(YCMHover)

" ctrlp
let g:ctrlp_working_path_mode = 'c'

" nerdtree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeMapOpenSplit = '-'
let NERDTreeMapOpenVSplit = '<bar>'

" lightline
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'solarized'
      \ }


" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Gemini CLI Cleanup: Beat the Hijack
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
augroup GeminiOverride
    autocmd!
    " This triggers specifically for Gemini's temp directory on macOS
    autocmd VimEnter */T/gemini-cli-tool-modify* call CleanGeminiMess()
augroup END

function! CleanGeminiMess()
    call Setup256ColorDiff()

    " 4. Fix the statusline 'OLD FILE' hijacking
    " This forces Vim to use its standard statusline again
    setlocal statusline=
endfunction

" Fix the :È...É characters (Bracketed Paste Mode)
if &term =~ "xterm" || &term =~ "screen" || &term =~ "tmux"
    set t_BE=
endif
