# linux specific
export TERM='xterm-256color'

export CLICOLOR=1
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;47:su=31;47:sg=31;46:tw=30;42:ow=30;43'
export PS1="\[\033[0;32m\]\u@\h\[$(tput sgr0)\] \[\033[0;34m\]\W\[$(tput sgr0)\]\$ "

alias ls='ls --color'

# no ctrl-s
stty -ixon
