#!/bin/bash

function cu() {
	dir="google3"
	if [[ -n "$1" ]]; then dir=$1; fi
	IFS="/" read -ra working_dirs <<< "$(pwd)"
	if [[ " ${working_dirs[@]} " =~ " $dir " ]]; then
		for (( i = ${#working_dirs[@]}-1 ; i >= 0 ; i-- )) ; do
			if [[ "${working_dirs[i]}" = "$dir" ]]; then
				break
			fi
			cd ..
		done
	else
		echo "No google3 dir found in path."
	fi
}
